<a href="https://colab.research.google.com/github/MalezhykDaniil/ML/blob/main/%D0%9B%D0%A01_%D0%9C%D0%9D_%D0%9C%D0%B0%D0%BB%D0%B5%D0%B6%D0%B8%D0%BA_3_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [ ]:
# Код студента
import numpy as np

np.__version__

'2.1.3'

## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [ ]:
# Код студента
arr = np.array([2, 4, 6, 8, 10])

arr

array([ 2,  4,  6,  8, 10])

In [ ]:
type(arr)

numpy.ndarray

### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [ ]:
# Код студента
zeros_arr = np.zeros(10)
ones_arr = np.ones(8)
sevens_arr = np.full(6, 7)

zeros_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
sevens_arr

array([7, 7, 7, 7, 7, 7])

### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
# Код студента
arr = np.arange(1, 21)
even_arr = np.arange(2, 21, 2)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
even_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
# Код студента
arr = np.linspace(0, 1, 11)

arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:
# Код студента
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)

matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:
# Код студента
np.ndim(matrix)


2

In [ ]:
np.shape(matrix)

(3, 4)

In [ ]:
np.size(matrix)

12

In [ ]:
matrix.dtype

dtype('int64')

### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [ ]:
# Код студента
arr = np.array([1.2, 3.5, 5.7, 7.9])
int_arr = arr.astype(int)

arr

array([1.2, 3.5, 5.7, 7.9])

In [ ]:
int_arr

array([1, 3, 5, 7])

## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [ ]:
# Код студента
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

arr[0]

np.int64(10)

In [ ]:
arr[-1]

np.int64(80)

In [ ]:
arr[2:6]

array([30, 40, 50, 60])

In [ ]:
arr[::2]

array([10, 30, 50, 70])

### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [ ]:
# Код студента
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

matrix[1, 2]

np.int64(7)

In [ ]:
matrix[1]

array([5, 6, 7, 8])

In [ ]:
matrix[:, 2]

array([ 3,  7, 11])

In [ ]:
matrix[1:, :2]

array([[ 5,  6],
       [ 9, 10]])

### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [ ]:
# Код студента
arr = np.arange(1, 16)
arr[5:10] = 0

arr

array([ 1,  2,  3,  4,  5,  0,  0,  0,  0,  0, 11, 12, 13, 14, 15])

## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [ ]:
# Код студента
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

a + b


array([11, 22, 33, 44, 55])

In [ ]:
a - b

array([ -9, -18, -27, -36, -45])

In [ ]:
a * b

array([ 10,  40,  90, 160, 250])

In [ ]:
a / b

array([0.1, 0.1, 0.1, 0.1, 0.1])

### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [ ]:
# Код студента
arr = np.array([4, 8, 15, 16, 23, 42])

np.sum(arr)

np.int64(108)

In [ ]:
np.mean(arr)

np.float64(18.0)

In [ ]:
np.min(arr)

np.int64(4)

In [ ]:
np.max(arr)

np.int64(42)

In [ ]:
np.median(arr)

np.float64(15.5)

In [ ]:
np.std(arr)

np.float64(12.315302134607444)

### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [ ]:
# Код студента
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

np.sum(matrix)

np.int64(45)

In [ ]:
np.sum(matrix, axis=0)

array([12, 15, 18])

In [ ]:
np.sum(matrix, axis=1)

array([ 6, 15, 24])

In [ ]:
np.mean(matrix, axis=0)

array([4., 5., 6.])

### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [ ]:
# Код студента
arr = np.arange(1, 11)

np.square(arr)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
np.sqrt(arr)

array([2.        , 2.82842712, 3.87298335, 4.        , 4.79583152,
       6.4807407 ])

In [ ]:
np.log(arr)

array([1.38629436, 2.07944154, 2.7080502 , 2.77258872, 3.13549422,
       3.73766962])

## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [ ]:
# Код студента
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

arr[arr > 15]

array([18, 21, 25, 30, 34])

In [ ]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [ ]:
arr[(arr >= 10) & (arr <= 30)]

array([10])

### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
arr[arr < 0] = 0

arr

array([ 0,  3,  0,  8,  0, 10,  0])

### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [ ]:
# Код студента
np.random.seed(42)

arr = np.random.randint(0, 101, size=20)

arr

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1,
       87, 29, 37])

In [ ]:
np.sum(arr > 50)

np.int64(0)

In [ ]:
np.sum(arr <= 50)

np.int64(7)

## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [ ]:
# Код студента
arr = np.arange(1, 25)

matrix_4x6 = arr.reshape(4, 6)
matrix_6x4 = arr.reshape(6, 4)
array_2x3x4 = arr.reshape(2, 3, 4)

matrix_4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
matrix_4x6.shape

(4, 6)

In [ ]:
matrix_6x4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
matrix_6x4.shape

(6, 4)

In [ ]:
array_2x3x4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
array_2x3x4.shape

(2, 3, 4)

### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [ ]:
# Код студента
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

vertical = np.vstack((A, B))
horizontal = np.hstack((A, B))

vertical

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
horizontal

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [ ]:
# Код студента
matrix = np.arange(1, 13).reshape(3, 4)

flat_1 = matrix.flatten()
flat_2 = matrix.ravel()

flat_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
flat_2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.array_equal(flat_1, flat_2)

True

## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [ ]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

a + b

array([ 3,  7, 11])

In [ ]:
a - b

array([1, 1, 1])

In [ ]:
a * 3

array([ 6, 12, 18])

In [ ]:
b * 3

array([ 3,  9, 15])

### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [ ]:
# Код студента
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)

np.int64(32)

In [ ]:
a @ b

np.int64(32)

### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:
# Код студента
v = np.array([3, 4])

norm = np.linalg.norm(v)
normalized_v = v / norm

norm

np.float64(5.0)

In [ ]:
normalized_v

array([0.6, 0.8])

### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [ ]:
# Код студента
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

cross_product = np.cross(a, b)

cross_product

array([0, 0, 1])

### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [ ]:
# Код студента
a = np.array([1, 2])
b = np.array([2, 1])

cos_angle = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
angle_degrees = np.degrees(np.arccos(cos_angle))

cos_angle

np.float64(0.7999999999999998)

In [ ]:
angle_degrees

np.float64(36.86989764584404)

## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [ ]:
# Код студента
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [ ]:
# Код студента
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [2, 0],
    [1, 2]
])

elementwise = A * B
matrix_product = A @ B
elementwise
# A * B множить відповідні елементи матриць.
# A @ B виконує матричне множення: рядки A множаться на стовпці B.

array([[2, 0],
       [3, 8]])

In [ ]:
matrix_product

array([[ 4,  4],
       [10,  8]])

### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [ ]:
# Код студента
A = np.array([
    [4, 7],
    [2, 6]
])

det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
check = A @ inv_A

det_A

np.float64(10.000000000000002)

In [ ]:
inv_A

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [ ]:
check

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [ ]:
# Код студента
A = np.array([
    [2, 1],
    [1, 3]
])

b = np.array([5, 6])

solution = np.linalg.solve(A, b)

solution

array([1.8, 1.4])

### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [ ]:
# Код студента
I = np.eye(4)

A = np.arange(1, 17).reshape(4, 4)
result = A @ I

I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
result

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [ ]:
np.allclose(A, result)

True

## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [ ]:
# Код студента
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = A + 10

result

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [ ]:
# Код студента
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

v = np.array([10, 20, 30])

result = A + v

result

# Вектор v додається до кожного рядка матриці A.

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
A = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

mean = np.mean(A, axis=0)
std = np.std(A, axis=0)

normalized = (A - mean) / std

normalized

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [ ]:
# Код студента
np.random.seed(42)

random_ints = np.random.randint(1, 101, size=10)
random_matrix = np.random.random((3, 3))
normal_values = np.random.normal(size=1000)

random_ints

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [ ]:
random_matrix

array([[0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264],
       [0.21233911, 0.18182497, 0.18340451]])

In [ ]:
np.mean(normal_values)

np.float64(0.02216865975826456)

In [ ]:
np.std(normal_values)

np.float64(0.9792284455184356)

### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [ ]:
# Код студента
grades = np.random.randint(0, 101, size=30)

grades

array([25,  2, 40, 59, 13, 74, 81, 11, 86, 11, 12, 24, 44, 18, 54, 99, 44,
        7, 92, 52, 54, 31, 50, 43, 81, 69, 17, 82, 21, 36])

In [ ]:
np.mean(grades)

np.float64(44.4)

In [ ]:
np.median(grades)

np.float64(43.5)

In [ ]:
np.max(grades)

np.int64(99)

In [ ]:
np.min(grades)

np.int64(2)

In [ ]:
np.sum(grades >= 60)

np.int64(8)

In [ ]:
np.mean(grades >= 90) * 100

np.float64(6.666666666666667)

## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [ ]:
# Код студента
sales = np.array([
    [120, 150, 170, 160],
    [80, 90, 100, 110],
    [200, 180, 210, 230]
])

product_totals = np.sum(sales, axis=1)
month_totals = np.sum(sales, axis=0)
best_product = np.argmax(product_totals) + 1
best_month = np.argmax(month_totals) + 1
product_means = np.mean(sales, axis=1)

product_totals

array([600, 380, 820])

In [ ]:
month_totals

array([400, 420, 480, 500])

In [ ]:
best_product

np.int64(3)

In [ ]:
best_month

np.int64(4)

In [ ]:
product_means

array([150.,  95., 205.])

### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [ ]:
# Код студента
matrix = np.random.randint(1, 21, size=(5, 5))

main_diag_sum = np.trace(matrix)
secondary_diag_sum = np.trace(np.fliplr(matrix))
row_max = np.max(matrix, axis=1)
col_min = np.min(matrix, axis=0)

mean_value = np.mean(matrix)
modified_matrix = matrix.copy()
modified_matrix[modified_matrix < mean_value] = 0

matrix

array([[ 9,  3, 10, 19,  3],
       [15,  1,  7, 12, 17],
       [20,  5,  4, 12, 20],
       [18, 17, 19,  9,  4],
       [ 2,  4,  2, 15,  2]])

In [ ]:
main_diag_sum

np.int64(25)

In [ ]:
secondary_diag_sum

np.int64(38)

In [ ]:
row_max

array([19, 17, 20, 19, 15])

In [ ]:
col_min

array([2, 1, 2, 9, 2])

In [ ]:
modified_matrix

array([[ 0,  0, 10, 19,  0],
       [15,  0,  0, 12, 17],
       [20,  0,  0, 12, 20],
       [18, 17, 19,  0,  0],
       [ 0,  0,  0, 15,  0]])

### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [ ]:
# Код студента
X = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [5, 7, 9]
])

d_12 = np.linalg.norm(X[0] - X[1])
d_13 = np.linalg.norm(X[0] - X[2])
d_23 = np.linalg.norm(X[1] - X[2])

d_12


np.float64(1.7320508075688772)

In [ ]:
d_13

np.float64(5.196152422706632)

In [ ]:
d_23

np.float64(6.928203230275509)

### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [ ]:
# Код студента
A = np.array([
    [1, 2, 3, 4],
    [2, 4, 6, 8],
    [3, 1, 4, 2],
    [5, 2, 1, 3]
])

norms = np.linalg.norm(A, axis=1, keepdims=True)
normalized_A = A / norms

norms

array([[ 5.47722558],
       [10.95445115],
       [ 5.47722558],
       [ 6.244998  ]])

In [ ]:
normalized_A

array([[0.18257419, 0.36514837, 0.54772256, 0.73029674],
       [0.18257419, 0.36514837, 0.54772256, 0.73029674],
       [0.54772256, 0.18257419, 0.73029674, 0.36514837],
       [0.80064077, 0.32025631, 0.16012815, 0.48038446]])

### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [ ]:
# Код студента
A = np.array([
    [1, 2, 1],
    [2, 1, -1],
    [3, -1, 2]
])

b = np.array([9, 8, 3])

x = np.linalg.solve(A, b)
check = A @ x

x

array([ 2.22222222,  3.44444444, -0.11111111])

In [ ]:
check

array([9., 8., 3.])

In [ ]:
b

array([9, 8, 3])

In [ ]:
np.allclose(check, b)

True

---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
